language: node_js
node_js:
- "8"

cache:
directories:
- "node_modules"

before_script:
  - npm install
  - psql -c 'create database quickcredit_test;' -U postgres

script:
- npm run test

after_success:
- npm run coverage

notifications:
  email: false
